const DEPARTMENTS = {
   
   CREATE_DEPARTMENT: 'CREATE_DEPARTMENT',

   GET_DEPARTMENTS : 'GET_DEPARTMENTS',

   DELETE_DEPARTMENT : 'DELETE_DEPARTMENT',

   ADD_DEPARTMENT_MEMBER: 'ADD_DEPARTMENT_MEMBER',

   GET_DEPARTMENT_MEMBER : 'GET_DEPARTMENT_MEMBER',

   GET_MANAGER_MEMBER : 'GET_MANAGER_MEMBER',

   DELETE_DEPARTMENT_MEMBER : 'DELETE_DEPARTMENT_MEMBER',

   GET_DEPARTMENT_MEMBERS : 'GET_DEPARTMENT_MEMBERS',

   GET_HODS : 'GET_HODS',

   GET_HODS_EMPLOYEES : 'GET_HODS_EMPLOYEES'

};

export default DEPARTMENTS