const TASK_CONSTANT = {
   
    CREATE_TASK: 'CREATE_TASK',

    GET_USER_TASK : 'GET_USER_TASK',
    
    GET_TASK_LIST_BY_STATUS : 'GET_TASK_LIST_BY_STATUS',
    
    GET_TASK_DETAIL : 'GET_TASK_DETAIL',

    SUBMIT_FOR_REVIEW : 'SUBMIT_FOR_REVIEW',

    MARK_AS_CLOSED : 'MARK_AS_CLOSED',

    ASSIGN_TASK_TO_EMPLOYEE : 'ASSIGN_TASK_TO_EMPLOYEE',
    
    GET_COMMENTS : 'GET_COMMENTS',

    ADD_COMMENTS : 'ADD_COMMENTS',

    SET_STATUS : 'SET_STATUS'

};

export default TASK_CONSTANT