const AUTH = {
   
    LOGIN: 'LOGIN',

    MS_LOGIN: 'MS_LOGIN',
    
    GET_USER_STATS: 'GET_USER_STATS',

    LOGOUT: 'LOGOUT_USER_API',

    GET_USER_ROLE : 'GET_USER_ROLE',
    
    GET_PROFILE : 'GET_PROFILE',
    
    SET_LOGIN_STATUS: 'SET_LOGIN_STATUS',
    
    SIGNUP: 'SIGNUP',
    
    TOGGLE_AUTH: 'TOGGLE_AUTH',
    
    VERIFY_OTP: 'VERIFY_OTP',

    MS_SIGNUP : 'MS_SIGNUP',

    RESEND_OTP : 'RESEND_OTP',

    REQUEST_OTP: 'REQUEST_OTP',

    FORGOT_PASSWORD_VERIFY_OTP : 'FORGOT_PASSWORD_VERIFY_OTP',

    RESET_PASSWORD: 'RESET_PASSWORD',

    CHANGE_PASSWORD : 'CHANGE_PASSWORD', 

    MS_VERIFY_LOGIN : 'MS_VERIFY_LOGIN',
    
    MS_VERIFY : 'MS_VERIFY',
  };
  
  export default AUTH;
  