const USERS = {

  GET_HR_USERS: 'GET_HR_USERS',

  GET_NON_HR_USERS: 'GET_NON_HR_USERS',

  GET_USER_STATS: 'GET_USER_STATS',

  GET_MANAGER: 'GET_MANAGER',

  UPDATE_STATUS: 'UPDATE_STATUS',

  UPDATE_PASSWORD: 'UPDATE_PASSWORD',

  UPDATE_USER_PERSONAL_DETAILS: 'UPDATE_USER_PERSONAL_DETAILS'
};

export default USERS;
